insert into INSURANCE_PLANS (PLAN_ID,PLAN_NAME,PLAN_HOLDER_NAME,PLAN_HOLDER_SSN,PLAN_STATUS) values(101,'SNAP','john','77789456','APPROVED');
insert into INSURANCE_PLANS (PLAN_ID,PLAN_NAME,PLAN_HOLDER_NAME,PLAN_HOLDER_SSN,PLAN_STATUS) values(102,'SNAP','nik','78789456','DENIED');
insert into INSURANCE_PLANS (PLAN_ID,PLAN_NAME,PLAN_HOLDER_NAME,PLAN_HOLDER_SSN,PLAN_STATUS) values(103,'CCAP','ak','4489456','APPROVED');
insert into INSURANCE_PLANS (PLAN_ID,PLAN_NAME,PLAN_HOLDER_NAME,PLAN_HOLDER_SSN,PLAN_STATUS) values(104,'QHP','smith','54889456','DENIED');
insert into INSURANCE_PLANS (PLAN_ID,PLAN_NAME,PLAN_HOLDER_NAME,PLAN_HOLDER_SSN,PLAN_STATUS) values(105,'CCAP','charls','74689456','APPROVED');
insert into INSURANCE_PLANS (PLAN_ID,PLAN_NAME,PLAN_HOLDER_NAME,PLAN_HOLDER_SSN,PLAN_STATUS) values(106,'QHP','shu','54589456','APPROVED');
insert into INSURANCE_PLANS (PLAN_ID,PLAN_NAME,PLAN_HOLDER_NAME,PLAN_HOLDER_SSN,PLAN_STATUS) values(107,'CCAP','ram','687889456','DENIED');